package GUIElements;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import backend.SNMPGETSET;
/**
 *
 * @author Joshua
 */
public class SNMPGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private SNMPGETSET snmpGS;
    public SNMPGUI() throws UnknownHostException {
        initComponents();
        TextArea_Responses.append("Hello. Program Initialized.\n");
        
        snmpGS = new SNMPGETSET(InetAddress.getByName(TextField_IPAddress.getText()));
        
        changeDescriptionOfOID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_Responses = new javax.swing.JTextArea();
        button_clear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        try{
            TextField_IPAddress = new javax.swing.JTextField(InetAddress.getLocalHost().getHostAddress());
            jLabel3 = new javax.swing.JLabel();
            TextField_Timeout = new javax.swing.JTextField();
            jLabel4 = new javax.swing.JLabel();
            TextField_RetryAmount = new javax.swing.JTextField("2");
            jLabel6 = new javax.swing.JLabel();
            ComboBox_PIDType = new javax.swing.JComboBox();
            jSeparator1 = new javax.swing.JSeparator();
            jLabel5 = new javax.swing.JLabel();
            ComboBox_OID = new javax.swing.JComboBox();
            text_Description = new javax.swing.JLabel();
            jSeparator2 = new javax.swing.JSeparator();
            jLabel7 = new javax.swing.JLabel();
            TextField_Value = new javax.swing.JTextField();
            Button_Send = new javax.swing.JButton();
            TextField_RepeatPIDSend = new javax.swing.JTextField("1");
            jLabel8 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            TextField_DelayBetween = new javax.swing.JTextField("0");

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel10.setText("To prepare your computer for running this program, please do the following:");

            jTextArea1.setEditable(false);
            jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
            jTextArea1.setColumns(20);
            jTextArea1.setLineWrap(true);
            jTextArea1.setRows(5);
            jTextArea1.setText("NOTE: It is assumed that basic Windows feature editing is known.\n\n1) Navigate to \"Turn Windows Features on or off\"\n2) Turn on \"Simple Network Management Protocol\" and everything below it.\n3) Navigate to \"View Local Services\" and double click \"SNMP Service\"\n4) Under the security tab, do the following:\n\ti. \"add\" a \"Read Only\" community named \"public\"\n\tii. \"add\" a \"Read Write\" community named \"writer\"\n\tiii. click \"Accept SNMP packets from any host\"\n5) Click apply and close\n6) Restart the service by right clicking and hitting \"restart\"\n\nYou are now ready to run this program.\n\nThis program was designed and created by Joshua Miller as a demo.");
            jScrollPane2.setViewportView(jTextArea1);

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(86, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Getting Started", jPanel2);

            TextArea_Responses.setColumns(20);
            TextArea_Responses.setRows(5);
            jScrollPane1.setViewportView(TextArea_Responses);

            button_clear.setText("Clear");
            button_clear.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    button_clearActionPerformed(evt);
                }
            });

            jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 0, 0));
            jLabel2.setText("****MAKE SURE TO CHECK OUT THE GETTING STARTED TAB FIRST***");

            jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jLabel1.setText("IP Address");

        }
        catch (UnknownHostException ex) {        }

        jLabel3.setText("Connection Timeout");

        jLabel4.setText("Retry Sending Amount");

        jLabel6.setText("PID Type");

        ComboBox_PIDType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Get", "Set"}));
        ComboBox_PIDType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBox_PIDTypeItemStateChanged(evt);
            }
        });

        jLabel5.setText("Object Identifier (OID)");

        ComboBox_OID.setEditable(true);
        ComboBox_OID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1.3.6.1.2.1.1.3.0", ".1.3.6.1.2.1.1.5.0", ".1.3.6.1.2.1.1.6.0", "1.3.6.1.2.1.4.1.0" }));
        ComboBox_OID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBox_OIDItemStateChanged(evt);
            }
        });
        ComboBox_OID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ComboBox_OIDFocusLost(evt);
            }
        });
        ComboBox_OID.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ComboBox_OIDInputMethodTextChanged(evt);
            }
        });

        text_Description.setForeground(new java.awt.Color(0, 0, 255));
        text_Description.setText("---");

        jLabel7.setText("Value to Send");

        TextField_Value.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_IPAddress)
                    .addComponent(TextField_Timeout)
                    .addComponent(TextField_RetryAmount)
                    .addComponent(ComboBox_OID, 0, 200, Short.MAX_VALUE)
                    .addComponent(TextField_Value)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(text_Description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ComboBox_PIDType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_IPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_Timeout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_RetryAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBox_PIDType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBox_OID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextField_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        TextField_Timeout.setText("2000");

        Button_Send.setText("Send PID");
        Button_Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SendActionPerformed(evt);
            }
        });

        TextField_RepeatPIDSend.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setText("Repeat PID Send Amount");

        jLabel9.setText("Delay Between Send");

        TextField_DelayBetween.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(TextField_RepeatPIDSend, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TextField_DelayBetween, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Send, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_RepeatPIDSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_DelayBetween, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(Button_Send, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Run Tests", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clearActionPerformed
        // TODO add your handling code here:
        TextArea_Responses.setText("");
    }//GEN-LAST:event_button_clearActionPerformed

    private void ComboBox_OIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBox_OIDItemStateChanged
        // TODO add your handling code here:
        changeDescriptionOfOID();
    }//GEN-LAST:event_ComboBox_OIDItemStateChanged

    private void ComboBox_PIDTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBox_PIDTypeItemStateChanged
        // TODO add your handling code here:
        if(ComboBox_PIDType.getSelectedItem().equals("Get"))
        {
            TextField_Value.setEnabled(false);
            TextField_RepeatPIDSend.setEnabled(true);
            TextField_DelayBetween.setEnabled(true);
        }
        else
        {
            TextField_Value.setEnabled(true);
            TextField_RepeatPIDSend.setEnabled(false);
            TextField_DelayBetween.setEnabled(false);
        }
    }//GEN-LAST:event_ComboBox_PIDTypeItemStateChanged

    private void ComboBox_OIDInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ComboBox_OIDInputMethodTextChanged
        // TODO add your handling code here:
       changeDescriptionOfOID();
    }//GEN-LAST:event_ComboBox_OIDInputMethodTextChanged

    private void Button_SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SendActionPerformed
        // TODO add your handling code here:
        if(ComboBox_PIDType.getSelectedItem().equals("Get"))
        {
            try {
                getSelected();
            } catch (IOException ex) {
                Logger.getLogger(SNMPGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(SNMPGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try {
                setSelected();
            } catch (IOException ex) {
                Logger.getLogger(SNMPGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Button_SendActionPerformed

    private void ComboBox_OIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ComboBox_OIDFocusLost
        // TODO add your handling code here:
        changeDescriptionOfOID();
    }//GEN-LAST:event_ComboBox_OIDFocusLost

    private void getSelected() throws IOException, InterruptedException
    {
        String str = "";
        for(int x = Integer.parseInt(TextField_RepeatPIDSend.getText()); x >0; x--)
        {
            str = snmpGS.snmpGet(snmpGS.getAddress(), SNMPGETSET.COMMUNITY_PUBLIC, ComboBox_OID.getSelectedItem().toString());
            TextArea_Responses.append(str+"\n");
            TextArea_Responses.update(TextArea_Responses.getGraphics());
            if(x!=1) Thread.sleep(Integer.parseInt(TextField_DelayBetween.getText()));
        }
    }
    
    private void setSelected() throws IOException
    {
        snmpGS.snmpSet(snmpGS.getAddress(), SNMPGETSET.COMMUNITY_WRITER, ComboBox_OID.getSelectedItem().toString(), TextField_Value.getText());
    }
    
    private void changeDescriptionOfOID()
    {
        if(ComboBox_OID.getSelectedItem().equals("1.3.6.1.2.1.1.3.0"))
        {
            text_Description.setText("Current UpTime. Not Editable");
        }
        else if(ComboBox_OID.getSelectedItem().equals(".1.3.6.1.2.1.1.5.0"))
        {
            text_Description.setText("Current ContactName. Editable");
        }
        else if(ComboBox_OID.getSelectedItem().equals(".1.3.6.1.2.1.1.6.0"))
        {
            text_Description.setText("Current Location. Editable");
        }
        else if(ComboBox_OID.getSelectedItem().equals("1.3.6.1.2.1.4.1.0"))
        {
            text_Description.setText("Current IPForwarding. Not Editable");
        }
        else
        {
            text_Description.setText("OID not described in program");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SNMPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SNMPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SNMPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SNMPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SNMPGUI().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(SNMPGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Send;
    private javax.swing.JComboBox ComboBox_OID;
    private javax.swing.JComboBox ComboBox_PIDType;
    private javax.swing.JTextArea TextArea_Responses;
    private javax.swing.JTextField TextField_DelayBetween;
    private javax.swing.JTextField TextField_IPAddress;
    private javax.swing.JTextField TextField_RepeatPIDSend;
    private javax.swing.JTextField TextField_RetryAmount;
    private javax.swing.JTextField TextField_Timeout;
    private javax.swing.JTextField TextField_Value;
    private javax.swing.JButton button_clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel text_Description;
    // End of variables declaration//GEN-END:variables
}
